### PR TITLE
Battery model capacity & resolution fix, two new pv_panels modeled

### PR DESCRIPTION
**Pull request by Lelezinski**
The following issues were fixed:

- The battery **capacity** value was hardcoded to 32mAh. It is now being correctly gathered from the .json config file.
- A **scaling factor** of 1000 was hardcoded in the battery process, tied to a SC_MS resolution simulation. It is now modified to allow the utilization of SC_SEC resolution. Even if other smaller resolutions should be uncommon to use, this is just a QUICKFIX and should allow in future the utilization of all the SC_* resolutions.

### CODE REVIEW

**Comment by Lelezinski** [comment]
The two new panels modeled are:

- **INDOOR PANEL**: TDM BCS BCSC421B1. Both in single cell and (more reasonable) 8 parallel / 4 serial configurations.
- **OUTDOOR PANEL**: PowerFilm MP3-37.

The light level traces are taken over a whole day with a time difference between consequent timestamps (i.e., rows in the trace files) of 1 second, to match the target resolution of the simulations.

It has to be noted that while the outdoor panel is modeled and simulated using irradiance levels (W/m2), the indoor panel works with illuminance levels (Lx = lm/m2). Although a conversion using known factors to the more common irradiance levels is possible, for the sake of simplicity both the modeling and the simulation of the indoor panel is done using the available illuminance levels.

**Comment by giovannipollo** [comment]
Hi @Lelezinski, 

Thanks for the pull request. First of all please update the main on this repository with yours, since we added son new stuff, to it's better to stay in sync. 

In addition to that, I have some comments:

1) I see there is not a folder with the .cpp file in the example folder (I only see it in the report). Please add it also here
2) The python scripts described in the report are not present, especially the "Workaround for PV Panel Trace File Reading Frequency", which may be useful in case someone wants to use another panel. Add this too, it would be good to integrate in the flow of messy, but in case it takes too long just put it in a utils folder. 

Thanks for the fix about the battery and the simulation. We really appreciate them!

**Comment by Lelezinski** [comment]
Hi @giovannipollo,

Thanks for the feedback, I updated this PR in this way:

1. Synced the main branch
2. Added the periodic_sensor code in the example folder
3. Provided the utility scripts in the utils folder with their readme. About them:
- `resolutioner.py` is a workaround for the resolution of the reading of the trace files. Instead of integrating this into the flow, I am assuming it would be both simpler and cleaner to just let the user choose a different resolution in the .json related to the trace file read (however, this would reach out of the scope of my project, so for now I leave it among the utils).
- The other scripts (`digitizer.py`, `mpp-calculator.py` and `plotter.py`) are still useful for modeling other harvesters/batteries into the simulator, but not strictly part of the flow. Thus, I also place them in the utils folder for you to choose whether to further integrate them in the flow somehow.

**Comment by giovannipollo** [comment]
Thanks a lot. For me everything seems good. I will merge it into the main!
Thanks for the contribution

**Pull request merged**
